# Generated by Django 5.1.3 on 2025-01-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0002_alter_quiz_options_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
