# Generated by Django 5.1.3 on 2025-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_manager', '0004_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='Answer', help_text='Texto da opção de resposta'),
        ),
    ]
